# SPDX-License-Identifier: Apache-2.0
"""Contract checks for the macOS validation-session Markdown summary helper."""

from __future__ import annotations

import argparse
import importlib.util
import json
import tempfile
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SUMMARY_TOOL = ROOT / "tools" / "macos_validation_session_summary.py"


def _load_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _load_summary_module():
    spec = importlib.util.spec_from_file_location(
        "macos_validation_session_summary_contract_target",
        SUMMARY_TOOL,
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("failed to load macOS validation-session summary helper")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def parse_summary_contract(text: str) -> dict[str, bool]:
    return {
        "declares_manifest_heading": "# AKVC macOS Validation Session Summary" in text,
        "declares_installation_snapshot_section": "## Installation Snapshot" in text,
        "declares_install_session_section": "## Install Session" in text,
        "declares_device_name_cohesion_section": "## Device Name Cohesion" in text,
        "declares_manual_app_validation_section": "## Manual App Validation Readiness" in text,
        "declares_runtime_command_tools_section": "## Runtime Command Tools" in text,
        "declares_runtime_asset_provenance_section": "## Runtime Asset Provenance" in text,
        "declares_runtime_topology_section": "## Runtime Topology" in text,
        "declares_sync_ipc_tool_section": "## Sync IPC Tool" in text,
        "declares_python_entrypoints_section": "## Python Entrypoints" in text,
        "declares_pyside6_demo_section": "## PySide6 Demo" in text,
        "declares_benchmark_matrix_section": "## Benchmark Matrix" in text,
        "declares_target_apps_section": "## Target Apps" in text,
        "declares_target_app_details_section": "## Target App Details" in text,
        "declares_acceptance_gates_section": "## Acceptance Gates" in text,
        "declares_acceptance_section": "## Acceptance" in text,
        "declares_acceptance_contract_section": "## Acceptance Contract" in text,
        "declares_artifacts_section": "## Artifacts" in text,
        "defines_sync_ipc_gate_prerequisites_helper": "def _sync_ipc_gate_prerequisites(" in text,
        "surfaces_artifact_check_passed": "artifact_check_passed" in text,
        "surfaces_acceptance_ready": "acceptance_ready" in text,
        "surfaces_manual_app_validation_ready": "manual_app_validation_ready" in text,
        "surfaces_manual_app_validation_failed_criteria": "manual_app_validation_failed_criteria" in text,
        "surfaces_manual_app_validation_unknown_criteria": "manual_app_validation_unknown_criteria" in text,
        "surfaces_manual_app_validation_blockers": "manual_app_validation_blockers" in text,
        "surfaces_acceptance_contract_present": "acceptance_contract_present" in text,
        "surfaces_acceptance_contract_passed": "acceptance_contract_passed" in text,
        "surfaces_effective_start_blocker": "effective_start_blocker_code" in text,
        "surfaces_effective_devices": "effective_devices" in text,
        "surfaces_effective_all_devices": "effective_all_devices" in text,
        "surfaces_effective_device_prefix": "effective_device_prefix" in text,
        "surfaces_device_name_cohesion_demo_match": "demo_camera_name_matches_effective_prefix" in text,
        "surfaces_device_name_cohesion_list_devices_match": "list_devices_binary_check_prefix_matches_effective_prefix" in text,
        "surfaces_effective_formats": "effective_supported_formats" in text,
        "surfaces_validation_devices": "validation_devices" in text,
        "surfaces_validation_all_devices": "validation_all_devices" in text,
        "surfaces_validation_device_prefix": "validation_device_prefix" in text,
        "surfaces_validation_install_phase": "validation_install_phase" in text,
        "surfaces_validation_install_status_devices": "validation_install_status_devices" in text,
        "surfaces_validation_install_status_all_devices": "validation_install_status_all_devices" in text,
        "surfaces_validation_install_device_prefix": "validation_install_device_prefix" in text,
        "surfaces_validation_install_ipc_ready": "validation_install_ipc_ready" in text,
        "surfaces_validation_install_ipc_environment_blocked": "validation_install_ipc_environment_blocked" in text,
        "surfaces_install_session_devices": "install_session_devices" in text,
        "surfaces_install_session_all_devices": "install_session_all_devices" in text,
        "surfaces_install_session_device_prefix": "install_session_device_prefix" in text,
        "surfaces_install_session_ipc_ready": "install_session_ipc_ready" in text,
        "surfaces_install_session_sync_ipc_success": "install_session_sync_ipc_success" in text,
        "surfaces_release_sync_ipc_tool_exists": "release_sync_ipc_tool_exists" in text,
        "surfaces_release_sync_ipc_tool_signed": "release_sync_ipc_tool_signed" in text,
        "surfaces_release_sync_ipc_tool_universal2_ready": "release_sync_ipc_tool_universal2_ready" in text,
        "surfaces_release_app_bundle_path": "release_app_bundle_path" in text,
        "surfaces_runtime_host_bundle_path": "runtime_host_bundle_path" in text,
        "surfaces_runtime_topology_kind": "runtime_topology_kind" in text,
        "surfaces_runtime_frame_path": "runtime_frame_path" in text,
        "surfaces_runtime_host_role": "runtime_host_role" in text,
        "surfaces_runtime_host_in_frame_hot_path": "runtime_host_in_frame_hot_path" in text,
        "surfaces_runtime_dedicated_host_daemon_required": "runtime_dedicated_host_daemon_required" in text,
        "surfaces_runtime_container_app_configured": "runtime_container_app_configured" in text,
        "surfaces_runtime_data_plane": "runtime_data_plane" in text,
        "surfaces_runtime_control_plane": "runtime_control_plane" in text,
        "surfaces_runtime_release_product_identity_consistent": "runtime_release_product_identity_consistent" in text,
        "surfaces_runtime_release_product_path_equal": "runtime_release_product_path_equal" in text,
        "surfaces_sync_ipc_gate_prerequisites": "Control-plane prerequisites satisfied" in text,
        "surfaces_entrypoints_contract_present": "entrypoints_contract_present" in text,
        "surfaces_entrypoints_contract_passed": "entrypoints_contract_passed" in text,
        "surfaces_entrypoints_contract_surface_complete": "entrypoints_contract_surface_complete" in text,
        "surfaces_entrypoints_contract_demo_case_complete": "entrypoints_contract_demo_case_complete" in text,
        "surfaces_entrypoints_contract_cli_case_complete": "entrypoints_contract_cli_case_complete" in text,
        "surfaces_entrypoints_contract_desktop_case_complete": "entrypoints_contract_desktop_case_complete" in text,
        "surfaces_sdk_contract_present": "sdk_contract_present" in text,
        "surfaces_sdk_contract_passed": "sdk_contract_passed" in text,
        "surfaces_sdk_contract_constructor_shape_aligned": "sdk_contract_constructor_shape_aligned" in text,
        "surfaces_sdk_contract_direct_sender_exports_present": "sdk_contract_direct_sender_exports_present" in text,
        "surfaces_validation_demo_mode": "validation_demo_mode" in text,
        "surfaces_validation_demo_camera_name": "validation_demo_camera_name" in text,
        "surfaces_validation_demo_frame_source_kind": "validation_demo_frame_source_kind" in text,
        "surfaces_validation_demo_python_entrypoint_kind": "validation_demo_python_entrypoint_kind" in text,
        "surfaces_validation_demo_sdk_streamer_factory_used": "validation_demo_sdk_streamer_factory_used" in text,
        "surfaces_validation_demo_sdk_latest_provider_factory_used": "validation_demo_sdk_latest_provider_factory_used" in text,
        "surfaces_validation_demo_sdk_direct_push_used": "validation_demo_sdk_direct_push_used" in text,
        "surfaces_validation_benchmark_kind": "validation_benchmark_kind" in text,
        "surfaces_validation_benchmark_matrix_profiles": "validation_benchmark_matrix_profiles" in text,
        "surfaces_benchmark_profiles_covered": "Profiles covered" in text,
        "surfaces_benchmark_required_profile_set_complete": "Required profile set complete" in text,
        "surfaces_benchmark_matrix_complete_gate": "benchmark_matrix_complete" in text,
        "surfaces_benchmark_fps_targets_met_gate": "benchmark_fps_targets_met" in text,
        "surfaces_macos_13_gate": "macos_13_plus_declared" in text,
        "surfaces_universal2_gate": "universal2_ready" in text,
        "surfaces_release_packaging_gate": "release_packaging_ready" in text,
        "surfaces_pyside6_gate": "pyside6_path_exercised" in text,
        "surfaces_python_entrypoints_gate": "python_entrypoints_consistent" in text,
        "surfaces_validation_passed_apps": "validation_passed_app_ids" in text,
        "surfaces_validation_validated_count": "validation_validated_apps" in text,
        "surfaces_validation_passed_count": "validation_passed_apps" in text,
        "surfaces_validation_failed_count": "validation_failed_apps" in text,
        "surfaces_validation_failed_apps": "validation_failed_app_ids" in text,
        "surfaces_validation_pending_apps": "validation_pending_app_ids" in text,
        "surfaces_validation_reviewed_apps": "validation_reviewed_app_ids" in text,
        "surfaces_validation_manual_ready": "validation_manual_validation_ready" in text,
        "surfaces_validation_manual_complete": "validation_manual_validation_complete" in text,
        "surfaces_validation_manual_all_passed": "validation_manual_validation_all_passed" in text,
        "surfaces_validation_observed_target_ids": "validation_observed_target_app_ids" in text,
        "surfaces_validation_unreviewed_apps": "validation_unreviewed_app_ids" in text,
        "surfaces_validation_target_id_set_complete": "validation_target_app_ids_complete" in text,
        "surfaces_validation_missing_target_ids": "validation_missing_target_app_ids" in text,
        "surfaces_validation_unexpected_target_ids": "validation_unexpected_target_app_ids" in text,
        "surfaces_validation_app_matrix": "validation_app_matrix" in text,
        "surfaces_validation_app_matrix_evidence": "device_listed" in text
        and "device_selected" in text
        and "preview_visible" in text
        and "screenshot" in text,
        "derives_target_app_groups_from_app_matrix": "_validation_app_ids_with_result" in text,
        "surfaces_target_apps_gate": "target_apps_all_passed" in text,
        "surfaces_system_camera_device_gate": "system_camera_device_visible" in text,
        "surfaces_auto_install_gate": "auto_install_ready" in text,
        "surfaces_runtime_assets_gate": "runtime_assets_packaged" in text,
        "surfaces_sync_ipc_control_plane_gate": "sync_ipc_control_plane_ready" in text,
        "surfaces_failed_criteria": "acceptance_failed_criteria" in text,
        "surfaces_unknown_criteria": "acceptance_unknown_criteria" in text,
        "surfaces_acceptance_counts": "Acceptance failed count" in text and "Acceptance unknown count" in text,
        "surfaces_acceptance_contract_counts": "Acceptance contract passed" in text and "## Acceptance Contract" in text,
        "surfaces_entrypoints_contract_artifact": "entrypoints_contract_report" in text,
        "surfaces_sdk_contract_artifact": "sdk_contract_report" in text,
        "surfaces_acceptance_contract_artifact": "acceptance_contract_report" in text,
    }


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")


def evaluate_render_cases() -> list[dict[str, Any]]:
    module = _load_summary_module()
    render_summary = module.render_summary
    cases: list[dict[str, Any]] = []

    fixtures = [
        {
            "name": "full_summary_includes_headings_and_app_groups",
            "acceptance_payload": {
                "summary": {
                    "failed_count": 1,
                    "unknown_count": 1,
                    "failed_criteria": ["target_apps_all_passed"],
                    "unknown_criteria": ["benchmark_1080p60_cpu_target_met"],
                    "manual_app_validation_ready": False,
                    "manual_app_validation_failed_criteria": ["system_camera_device_visible"],
                    "manual_app_validation_unknown_criteria": ["notarization_tooling_ready"],
                    "manual_app_validation_blockers": [
                        "system_camera_device_visible",
                        "notarization_tooling_ready",
                    ],
                },
                "criteria": [
                    {"name": "macos_13_plus_declared", "status": "pass"},
                    {"name": "universal2_ready", "status": "pass"},
                    {"name": "release_packaging_ready", "status": "pass"},
                    {"name": "pyside6_path_exercised", "status": "pass"},
                    {"name": "python_entrypoints_consistent", "status": "pass"},
                    {"name": "target_apps_all_passed", "status": "fail"},
                    {"name": "system_camera_device_visible", "status": "pass"},
                    {"name": "benchmark_matrix_complete", "status": "pass"},
                    {"name": "benchmark_fps_targets_met", "status": "pass"},
                    {"name": "benchmark_1080p60_cpu_target_met", "status": "unknown"},
                    {"name": "auto_install_ready", "status": "pass"},
                    {"name": "signing_evidence_ready", "status": "pass"},
                    {"name": "notarization_tooling_ready", "status": "unknown"},
                    {"name": "runtime_assets_packaged", "status": "pass"},
                ],
            },
            "manifest_payload": {
                "artifacts": {
                    "validation_report": "validation-report.json",
                    "artifact_check_report": "session-manifest-check.json",
                    "acceptance_report": "session-acceptance.json",
                    "acceptance_contract_report": "session-acceptance-contract.json",
                    "manual_template": "manual-results.template.json",
                    "entrypoints_contract_report": "entrypoints-contract.json",
                },
                "summary": {
                    "artifact_check_passed": True,
                    "acceptance_ready": False,
                    "manual_app_validation_ready": False,
                    "acceptance_contract_present": True,
                    "acceptance_contract_passed": True,
                    "effective_start_ready": False,
                    "effective_start_blocker_code": "device_not_visible",
                    "effective_devices": [],
                    "effective_all_devices": ["FaceTime HD Camera"],
                    "effective_device_prefix": "AK Virtual Camera",
                    "validation_devices": ["AK Virtual Camera"],
                    "validation_all_devices": ["FaceTime HD Camera", "AK Virtual Camera"],
                    "validation_device_prefix": "AK Virtual Camera",
                    "effective_supported_formats": ["1920x1080@30/60 NV12"],
                    "effective_supported_frame_rates": [30, 60],
                    "validation_install_present": True,
                    "validation_install_success": True,
                    "validation_install_phase": "installed_visible",
                    "validation_install_start_ready": True,
                    "validation_install_start_blocker_code": "ready",
                    "validation_install_status_devices": ["AK Virtual Camera"],
                    "validation_install_status_all_devices": ["FaceTime HD Camera", "AK Virtual Camera"],
                    "validation_install_device_prefix": "AK Virtual Camera",
                    "validation_install_supported_formats": ["1920x1080@30/60 NV12"],
                    "validation_install_supported_frame_rates": [30, 60],
                    "validation_install_ipc_probe_present": True,
                    "validation_install_ipc_ready": True,
                    "validation_install_ipc_environment_blocked": False,
                    "validation_install_ipc_direct_open_errno": 0,
                    "install_session_present": True,
                    "install_session_success": True,
                    "install_session_start_ready": True,
                    "install_session_start_blocker_code": "ready",
                    "install_session_devices": [],
                    "install_session_all_devices": ["FaceTime HD Camera"],
                    "install_session_device_prefix": "AK Virtual Camera",
                    "install_session_ipc_probe_present": True,
                    "install_session_ipc_ready": True,
                    "install_session_ipc_environment_blocked": False,
                    "install_session_ipc_direct_open_errno": 0,
                    "install_session_sync_ipc_present": True,
                    "install_session_sync_ipc_supported": True,
                    "install_session_sync_ipc_success": True,
                    "install_session_sync_ipc_phase": "sync_command_succeeded",
                    "install_session_sync_ipc_shared_memory_name": "/akvc-session",
                    "install_session_sync_ipc_transport": "shared_memory_ringbuffer",
                    "install_session_sync_ipc_returncode": 0,
                    "release_sync_ipc_tool_exists": True,
                    "release_sync_ipc_tool_signed": True,
                    "release_sync_ipc_tool_universal2_ready": True,
                    "release_app_bundle_path": "/Applications/Amaran Desktop.app",
                    "release_extension_bundle_path": "/Applications/Amaran Desktop.app/Contents/Library/SystemExtensions/com.sidus.amaran-desktop.cameraextension.systemextension",
                    "release_sync_ipc_tool_path": "/Applications/Amaran Desktop.app/Contents/MacOS/akvc-macos-sync-ipc",
                    "release_pkg_path": "/tmp/VirtualCamera.pkg",
                    "runtime_host_bundle_path": "/Applications/Amaran Desktop.app",
                    "runtime_extension_bundle_path": "/Applications/Amaran Desktop.app/Contents/Library/SystemExtensions/com.sidus.amaran-desktop.cameraextension.systemextension",
                    "runtime_topology_kind": "camera_extension_direct_framebus",
                    "runtime_frame_path": "python_sdk -> shared_memory_ringbuffer -> camera_extension -> system_camera_device -> client_app",
                    "runtime_host_role": "container_activation_command_bridge",
                    "runtime_host_in_frame_hot_path": False,
                    "runtime_dedicated_host_daemon_required": False,
                    "runtime_container_app_configured": True,
                    "runtime_data_plane": "shared_memory_ringbuffer",
                    "runtime_control_plane": "host_activation_plus_sync_ipc",
                    "runtime_release_product_identity_consistent": True,
                    "runtime_release_product_path_equal": False,
                    "entrypoints_contract_present": True,
                    "entrypoints_contract_passed": True,
                    "entrypoints_contract_surface_complete": True,
                    "entrypoints_contract_demo_case_complete": True,
                    "entrypoints_contract_cli_case_complete": True,
                    "entrypoints_contract_desktop_case_complete": True,
                    "validation_demo_present": True,
                    "validation_demo_mode": "latest-provider",
                    "validation_demo_mode_supported": True,
                    "validation_demo_width": 1920,
                    "validation_demo_height": 1080,
                    "validation_demo_fps": 60.0,
                    "validation_demo_duration": 5.0,
                    "validation_demo_camera_name": "AKVC Demo",
                    "validation_demo_consumer_count": 2,
                    "validation_demo_video_path": "demo.mp4",
                    "validation_demo_frame_source_kind": "latest_frame_provider",
                    "validation_demo_python_entrypoint_kind": "create_latest_frame_provider+create_pyside6_streamer.start_latest_frame_stream",
                    "validation_demo_sdk_streamer_factory_used": True,
                    "validation_demo_sdk_latest_provider_factory_used": True,
                    "validation_demo_sdk_direct_push_used": False,
                    "list_devices_binary_check_device_prefix": "AK Virtual Camera",
                    "validation_benchmark_kind": "benchmark_matrix",
                    "validation_benchmark_matrix_profiles": [
                        {
                            "profile_name": "720p30",
                            "width": 1280,
                            "height": 720,
                            "fps": 30.0,
                            "fps_target_met": True,
                            "cpu_target_applies": False,
                            "cpu_target_met": None,
                            "actual_fps": 29.8,
                            "cpu_percent": 3.1,
                            "avg_latency_ms": 0.7,
                        },
                        {
                            "profile_name": "1080p60",
                            "width": 1920,
                            "height": 1080,
                            "fps": 60.0,
                            "fps_target_met": True,
                            "cpu_target_applies": True,
                            "cpu_target_met": True,
                            "actual_fps": 59.6,
                            "cpu_percent": 8.4,
                            "avg_latency_ms": 1.1,
                        },
                    ],
                    "validation_passed_app_ids": ["zoom", "obs"],
                    "validation_reviewed_app_ids": ["teams", "zoom", "obs"],
                    "validation_failed_app_ids": ["teams"],
                    "validation_pending_app_ids": ["google_meet"],
                    "validation_skipped_app_ids": ["quicktime"],
                    "validation_unreviewed_app_ids": ["facetime"],
                    "validation_observed_target_app_ids": [
                        "google_meet",
                        "obs",
                        "quicktime",
                        "teams",
                        "zoom",
                    ],
                    "validation_missing_target_app_ids": ["facetime"],
                    "validation_unexpected_target_app_ids": [],
                    "validation_target_app_ids_complete": False,
                    "validation_validated_apps": 3,
                    "validation_passed_apps": 2,
                    "validation_failed_apps": 1,
                    "validation_pending_apps": 1,
                    "validation_skipped_apps": 1,
                    "validation_manual_validation_ready": True,
                    "validation_manual_validation_complete": False,
                    "validation_manual_validation_all_passed": False,
                    "validation_app_matrix": {
                        "zoom": {
                            "name": "Zoom",
                            "reviewed": True,
                            "validated": True,
                            "result": "pass",
                            "notes": "preview visible",
                            "ready": True,
                            "status": "ok",
                            "evidence": {
                                "device_listed": True,
                                "device_selected": True,
                                "preview_visible": True,
                                "screenshot": "artifacts/zoom.png",
                            },
                        },
                        "teams": {
                            "name": "Teams",
                            "reviewed": True,
                            "validated": False,
                            "result": "fail",
                            "notes": "device not shown",
                            "ready": True,
                            "status": "missing",
                            "evidence": {
                                "device_listed": False,
                                "device_selected": False,
                                "preview_visible": False,
                                "screenshot": "",
                            },
                        },
                    },
                    "acceptance_failed_criteria": ["target_apps_all_passed"],
                    "acceptance_unknown_criteria": ["benchmark_1080p60_cpu_target_met"],
                    "manual_app_validation_failed_criteria": ["system_camera_device_visible"],
                    "manual_app_validation_unknown_criteria": ["notarization_tooling_ready"],
                    "manual_app_validation_blockers": [
                        "system_camera_device_visible",
                        "notarization_tooling_ready",
                    ],
                },
            },
            "expected_substrings": [
                "# AKVC macOS Validation Session Summary",
                "## Installation Snapshot",
                "## Install Session",
                "## Device Name Cohesion",
                "## Manual App Validation Readiness",
                "## Runtime Command Tools",
                "## Runtime Asset Provenance",
                "## Runtime Topology",
                "## Sync IPC Tool",
                "## Python Entrypoints",
                "## PySide6 Demo",
                "## Benchmark Matrix",
                "## Target Apps",
                "## Target App Details",
                "## Acceptance Gates",
                "## Acceptance",
                "## Acceptance Contract",
                "## Artifacts",
                "- Artifact check passed: `yes`",
                "- Acceptance ready: `no`",
                "- Manual app validation ready: `no`",
                "- Acceptance contract passed: `yes`",
                "- Effective start blocker: `device_not_visible`",
                "- Effective devices: `-`",
                "- Effective all devices: `FaceTime HD Camera`",
                "- Effective device prefix: `AK Virtual Camera`",
                "- Demo camera name matches effective prefix: `no`",
                "- Validation device prefix matches effective prefix: `yes`",
                "- Install snapshot device prefix matches effective prefix: `yes`",
                "- Install session device prefix matches effective prefix: `yes`",
                "- List-devices binary-check prefix matches effective prefix: `yes`",
                "- Devices: `AK Virtual Camera`",
                "- All devices: `FaceTime HD Camera, AK Virtual Camera`",
                "- Device prefix: `AK Virtual Camera`",
                "- Present: `yes`",
                "- Success: `yes`",
                "- Phase: `installed_visible`",
                "- Status devices: `AK Virtual Camera`",
                "- Status all devices: `FaceTime HD Camera, AK Virtual Camera`",
                "- IPC probe present: `yes`",
                "- IPC ready: `yes`",
                "- IPC environment blocked: `no`",
                "- Session present: `yes`",
                "- Session success: `yes`",
                "- Session devices: `-`",
                "- Session all devices: `FaceTime HD Camera`",
                "- Session device prefix: `AK Virtual Camera`",
                "- Session IPC ready: `yes`",
                "- Exists: `yes`",
                "- Signed: `yes`",
                "- Universal2 ready: `yes`",
                "- Release container app bundle path: `/Applications/Amaran Desktop.app`",
                "- Runtime/release product identity consistent: `yes`",
                "- Runtime/release product path equal: `no`",
                "- Topology kind: `camera_extension_direct_framebus`",
                "- Host in frame hot path: `no`",
                "- Dedicated host daemon required: `no`",
                "- Data plane: `shared_memory_ringbuffer`",
                "- Control plane: `host_activation_plus_sync_ipc`",
                "- Control-plane prerequisites satisfied: `yes`",
                "- Present: `yes`",
                "- Passed: `yes`",
                "- Surface complete: `yes`",
                "- Demo case complete: `yes`",
                "- CLI case complete: `yes`",
                "- Desktop case complete: `yes`",
                "- Present: `yes`",
                "- Mode: `latest-provider`",
                "- Mode supported: `yes`",
                "- Width: `1920`",
                "- Height: `1080`",
                "- FPS: `60.0`",
                "- Duration: `5.0`",
                "- Camera name: `AKVC Demo`",
                "- Consumer count: `2`",
                "- Video path: `demo.mp4`",
                "- Frame source: `latest_frame_provider`",
                "- Python entrypoint: `create_latest_frame_provider+create_pyside6_streamer.start_latest_frame_stream`",
                "- SDK streamer factory used: `yes`",
                "- SDK latest-provider factory used: `yes`",
                "- SDK direct push used: `no`",
                "- Kind: `benchmark_matrix`",
                "- Profiles covered: `720p30, 1080p60`",
                "- Required profile set complete: `no`",
                "- Matrix complete gate: `pass`",
                "- FPS targets met: `pass`",
                "- 1080p60 CPU target met: `unknown`",
                "- 720p30: 1280x720@30.0 fps_target_met=`yes` cpu_target_applies=`no` cpu_target_met=`unknown` actual_fps=`29.8` cpu_percent=`3.1` avg_latency_ms=`0.7`",
                "- 1080p60: 1920x1080@60.0 fps_target_met=`yes` cpu_target_applies=`yes` cpu_target_met=`yes` actual_fps=`59.6` cpu_percent=`8.4` avg_latency_ms=`1.1`",
                "- Ready: `no`",
                "- Failed prerequisites: `系统已枚举到虚拟摄像头`",
                "- Unknown prerequisites: `公证工具链已就绪`",
                "- Combined blockers: `系统已枚举到虚拟摄像头, 公证工具链已就绪`",
                "- macOS 13+ declared: `pass`",
                "- Universal2 ready: `pass`",
                "- Release packaging ready: `pass`",
                "- PySide6 path exercised: `pass`",
                "- Python entrypoints consistent: `pass`",
                "- Target apps all passed: `fail`",
                "- System camera device visible: `pass`",
                "- Benchmark matrix complete: `pass`",
                "- Benchmark FPS targets met: `pass`",
                "- Auto install ready: `pass`",
                "- Signing evidence ready: `pass`",
                "- Notarization tooling ready: `unknown`",
                "- Runtime assets packaged: `pass`",
                "- Sync IPC control plane ready: `unknown`",
                "- Validated apps: `3`",
                "- Passed apps: `2`",
                "- Failed apps: `1`",
                "- Pending apps: `1`",
                "- Skipped apps: `1`",
                "- Manual validation ready: `yes`",
                "- Review complete: `no`",
                "- All target apps passed manually: `no`",
                "- Passed: `zoom, obs`",
                "- Failed: `teams`",
                "- Pending: `google_meet`",
                "- Skipped: `quicktime`",
                "- Reviewed: `teams, zoom, obs`",
                "- Unreviewed: `facetime`",
                "- Observed target ids: `google_meet, obs, quicktime, teams, zoom`",
                "- Target id set complete: `no`",
                "- Missing target ids: `facetime`",
                "- Unexpected target ids: `-`",
                "- teams (Teams): result=`fail` reviewed=`yes` validated=`no` ready=`yes` status=`missing` steps=`0` checks=`0` listed=`no` selected=`no` preview=`no` notes=`device not shown`",
                "- zoom (Zoom): result=`pass` reviewed=`yes` validated=`yes` ready=`yes` status=`ok` steps=`0` checks=`0` listed=`yes` selected=`yes` preview=`yes` screenshot=`artifacts/zoom.png` notes=`preview visible`",
                "- Failed criteria: `target_apps_all_passed`",
                "- Unknown criteria: `benchmark_1080p60_cpu_target_met`",
                "- Acceptance failed count: `1`",
                "- Acceptance unknown count: `1`",
                "- Passed: `yes`",
                "- acceptance_contract_report: `session-acceptance-contract.json`",
                "- entrypoints_contract_report: `entrypoints-contract.json`",
            ],
        },
        {
            "name": "missing_values_render_as_unknown_or_dash",
            "acceptance_payload": {"summary": {}},
            "manifest_payload": {
                "artifacts": {
                    "acceptance_report": "session-acceptance.json",
                },
                "summary": {
                    "artifact_check_passed": None,
                    "acceptance_ready": None,
                    "manual_app_validation_ready": None,
                    "acceptance_contract_present": None,
                    "acceptance_contract_passed": None,
                    "effective_start_ready": None,
                    "effective_start_blocker_code": None,
                    "effective_supported_formats": None,
                    "effective_supported_frame_rates": None,
                    "validation_passed_app_ids": None,
                    "validation_failed_app_ids": None,
                    "validation_pending_app_ids": None,
                    "validation_skipped_app_ids": None,
                    "validation_unreviewed_app_ids": None,
                    "acceptance_failed_criteria": None,
                    "acceptance_unknown_criteria": None,
                    "manual_app_validation_failed_criteria": None,
                    "manual_app_validation_unknown_criteria": None,
                    "manual_app_validation_blockers": None,
                },
            },
            "expected_substrings": [
                "- Artifact check passed: `unknown`",
                "- Acceptance ready: `unknown`",
                "- Manual app validation ready: `unknown`",
                "- Acceptance contract passed: `unknown`",
                "- Effective start blocker: `-`",
                "- Effective devices: `-`",
                "- Effective all devices: `-`",
                "- Effective device prefix: `-`",
                "- Demo camera name matches effective prefix: `unknown`",
                "- Validation device prefix matches effective prefix: `unknown`",
                "- Install snapshot device prefix matches effective prefix: `unknown`",
                "- Install session device prefix matches effective prefix: `unknown`",
                "- List-devices binary-check prefix matches effective prefix: `unknown`",
                "- Effective formats: `-`",
                "- Effective frame rates: `-`",
                "- Devices: `-`",
                "- All devices: `-`",
                "- Device prefix: `-`",
                "- Present: `unknown`",
                "- Success: `unknown`",
                "- Phase: `-`",
                "- Status devices: `-`",
                "- Status all devices: `-`",
                "- IPC ready: `unknown`",
                "- IPC environment blocked: `unknown`",
                "- Session present: `unknown`",
                "- Session success: `unknown`",
                "- Session devices: `-`",
                "- Session all devices: `-`",
                "- Session device prefix: `-`",
                "- Session IPC ready: `unknown`",
                "- Exists: `unknown`",
                "- Signed: `unknown`",
                "- Universal2 ready: `unknown`",
                "- Control-plane prerequisites satisfied: `unknown`",
                "- Surface complete: `unknown`",
                "- Demo case complete: `unknown`",
                "- CLI case complete: `unknown`",
                "- Desktop case complete: `unknown`",
                "- Mode: `-`",
                "- Mode supported: `unknown`",
                "- Width: `-`",
                "- Height: `-`",
                "- FPS: `-`",
                "- Duration: `-`",
                "- Camera name: `-`",
                "- Consumer count: `-`",
                "- Video path: `-`",
                "- Frame source: `-`",
                "- Python entrypoint: `-`",
                "- SDK streamer factory used: `unknown`",
                "- SDK latest-provider factory used: `unknown`",
                "- SDK direct push used: `unknown`",
                "- Ready: `unknown`",
                "- Failed prerequisites: `-`",
                "- Unknown prerequisites: `-`",
                "- Combined blockers: `-`",
                "- macOS 13+ declared: `unknown`",
                "- Universal2 ready: `unknown`",
                "- Release packaging ready: `unknown`",
                "- PySide6 path exercised: `unknown`",
                "- Python entrypoints consistent: `unknown`",
                "- Target apps all passed: `unknown`",
                "- System camera device visible: `unknown`",
                "- Benchmark matrix complete: `unknown`",
                "- Benchmark FPS targets met: `unknown`",
                "- Auto install ready: `unknown`",
                "- Signing evidence ready: `unknown`",
                "- Notarization tooling ready: `unknown`",
                "- Runtime assets packaged: `unknown`",
                "- Sync IPC control plane ready: `unknown`",
                "- Validated apps: `-`",
                "- Passed apps: `-`",
                "- Failed apps: `-`",
                "- Pending apps: `-`",
                "- Skipped apps: `-`",
                "- Manual validation ready: `unknown`",
                "- Review complete: `unknown`",
                "- All target apps passed manually: `unknown`",
                "- Passed: `-`",
                "- Failed: `-`",
                "- Pending: `-`",
                "- Skipped: `-`",
                "- Reviewed: `-`",
                "- Unreviewed: `-`",
                "- Observed target ids: `-`",
                "- Target id set complete: `unknown`",
                "- Missing target ids: `-`",
                "- Unexpected target ids: `-`",
                "- `-`",
                "- Failed criteria: `-`",
                "- Unknown criteria: `-`",
                "- Acceptance failed count: `-`",
                "- Acceptance unknown count: `-`",
                "- Present: `unknown`",
                "- Passed: `unknown`",
            ],
        },
        {
            "name": "manifest_summary_gate_fallback_without_acceptance_report",
            "acceptance_payload": None,
            "manifest_payload": {
                "artifacts": {},
                "summary": {
                    "acceptance_ready": False,
                    "manual_app_validation_ready": False,
                    "acceptance_contract_present": None,
                    "acceptance_contract_passed": None,
                    "acceptance_failed_count": 1,
                    "acceptance_unknown_count": 2,
                    "manual_app_validation_failed_criteria": ["system_camera_device_visible"],
                    "manual_app_validation_unknown_criteria": ["benchmark_matrix_complete"],
                    "manual_app_validation_blockers": [
                        "system_camera_device_visible",
                        "benchmark_matrix_complete",
                    ],
                    "macos_13_plus_declared": "pass",
                    "universal2_ready": "pass",
                    "release_packaging_ready": "pass",
                    "pyside6_path_exercised": "pass",
                    "python_entrypoints_consistent": "pass",
                    "validation_validated_apps": 3,
                    "validation_passed_apps": 1,
                    "validation_failed_apps": 1,
                    "validation_pending_apps": 2,
                    "validation_skipped_apps": 0,
                    "target_apps_all_passed": "fail",
                    "system_camera_device_visible": "pass",
                    "benchmark_matrix_complete": "fail",
                    "benchmark_fps_targets_met": "unknown",
                    "auto_install_ready": "pass",
                    "signing_evidence_ready": "pass",
                    "notarization_tooling_ready": "unknown",
                    "benchmark_1080p60_cpu_target_met": "unknown",
                    "runtime_assets_packaged": "pass",
                    "sync_ipc_control_plane_ready": "pass",
                    "release_command_tools_exist": True,
                    "release_command_tools_signed": True,
                    "release_command_tools_universal2_ready": True,
                    "release_pkg_payload_appledouble_clean": True,
                    "release_sync_ipc_tool_exists": True,
                    "release_sync_ipc_tool_signed": True,
                    "release_sync_ipc_tool_universal2_ready": True,
                    "install_session_sync_ipc_present": True,
                    "install_session_sync_ipc_supported": True,
                    "install_session_sync_ipc_success": True,
                    "install_session_sync_ipc_phase": "sync_command_succeeded",
                    "install_session_sync_ipc_shared_memory_name": "/akvc-session",
                    "install_session_sync_ipc_transport": "shared_memory_ringbuffer",
                },
            },
            "expected_substrings": [
                "- Acceptance ready: `no`",
                "- Manual app validation ready: `no`",
                "- Acceptance contract passed: `unknown`",
                "- All tools exist: `yes`",
                "- All tools signed: `yes`",
                "- All tools universal2 ready: `yes`",
                "- PKG payload AppleDouble clean: `yes`",
                "- Exists: `yes`",
                "- Signed: `yes`",
                "- Universal2 ready: `yes`",
                "- Runtime sync present: `yes`",
                "- Runtime sync success: `yes`",
                "- Control-plane prerequisites satisfied: `yes`",
                "- Surface complete: `unknown`",
                "- Demo case complete: `unknown`",
                "- CLI case complete: `unknown`",
                "- Desktop case complete: `unknown`",
                "- Ready: `no`",
                "- Failed prerequisites: `系统已枚举到虚拟摄像头`",
                "- Unknown prerequisites: `性能矩阵完整`",
                "- Combined blockers: `系统已枚举到虚拟摄像头, 性能矩阵完整`",
                "- Validated apps: `3`",
                "- Passed apps: `1`",
                "- Failed apps: `1`",
                "- Pending apps: `2`",
                "- Skipped apps: `0`",
                "- Manual validation ready: `unknown`",
                "- Review complete: `unknown`",
                "- All target apps passed manually: `unknown`",
                "- Reviewed: `-`",
                "- Unreviewed: `-`",
                "- Observed target ids: `-`",
                "- Target id set complete: `unknown`",
                "- Missing target ids: `-`",
                "- Unexpected target ids: `-`",
                "- Mode: `-`",
                "- Consumer count: `-`",
                "- Frame source: `-`",
                "- Python entrypoint: `-`",
                "- macOS 13+ declared: `pass`",
                "- Universal2 ready: `pass`",
                "- Target apps all passed: `fail`",
                "- System camera device visible: `pass`",
                "- Benchmark matrix complete: `fail`",
                "- Benchmark FPS targets met: `unknown`",
                "- Auto install ready: `pass`",
                "- Python entrypoints consistent: `pass`",
                "- Runtime assets packaged: `pass`",
                "- Sync IPC control plane ready: `pass`",
                "- `-`",
                "- Acceptance failed count: `1`",
                "- Acceptance unknown count: `2`",
                "- Present: `unknown`",
                "- Passed: `unknown`",
            ],
        },
        {
            "name": "target_app_groups_derive_from_matrix_when_counts_missing",
            "acceptance_payload": None,
            "manifest_payload": {
                "artifacts": {},
                "summary": {
                    "validation_app_matrix": {
                        "zoom": {
                            "name": "Zoom",
                            "reviewed": True,
                            "validated": True,
                            "result": "pass",
                            "notes": "preview visible",
                            "ready": True,
                            "status": "ok",
                        },
                        "teams": {
                            "name": "Teams",
                            "reviewed": True,
                            "validated": False,
                            "result": "fail",
                            "notes": "device missing",
                            "ready": True,
                            "status": "missing",
                        },
                        "google_meet": {
                            "name": "Google Meet",
                            "reviewed": True,
                            "validated": False,
                            "result": "pending",
                            "notes": "manual verification pending",
                            "ready": True,
                            "status": "pending",
                        },
                        "quicktime": {
                            "name": "QuickTime",
                            "reviewed": False,
                            "validated": False,
                            "result": "skipped",
                            "notes": "not yet reviewed",
                            "ready": True,
                            "status": "pending_review",
                        },
                    },
                },
            },
            "expected_substrings": [
                "- Validated apps: `3`",
                "- Passed apps: `1`",
                "- Failed apps: `1`",
                "- Pending apps: `1`",
                "- Skipped apps: `1`",
                "- Manual validation ready: `unknown`",
                "- Review complete: `unknown`",
                "- All target apps passed manually: `unknown`",
                "- Passed: `zoom`",
                "- Failed: `teams`",
                "- Pending: `google_meet`",
                "- Skipped: `quicktime`",
                "- Reviewed: `google_meet, teams, zoom`",
                "- Unreviewed: `quicktime`",
                "- Observed target ids: `-`",
                "- Target id set complete: `unknown`",
                "- Missing target ids: `-`",
                "- Unexpected target ids: `-`",
                "- quicktime (QuickTime): result=`skipped` reviewed=`no` validated=`no` ready=`yes` status=`pending_review` steps=`0` checks=`0` listed=`unknown` selected=`unknown` preview=`unknown` notes=`not yet reviewed`",
            ],
        },
    ]

    with tempfile.TemporaryDirectory() as td:
        tmpdir = Path(td)
        for fixture in fixtures:
            manifest = tmpdir / f"{fixture['name']}-session-manifest.json"
            acceptance_report = tmpdir / f"{fixture['name']}-session-acceptance.json"
            _write_json(acceptance_report, fixture["acceptance_payload"])
            manifest_payload = dict(fixture["manifest_payload"])
            artifacts = dict(manifest_payload.get("artifacts", {}))
            if fixture["acceptance_payload"] is not None:
                artifacts["acceptance_report"] = str(acceptance_report)
            manifest_payload["artifacts"] = artifacts
            _write_json(manifest, manifest_payload)
            rendered = str(render_summary(manifest))
            substring_matches = {
                item: item in rendered for item in fixture["expected_substrings"]
            }
            cases.append(
                {
                    "name": fixture["name"],
                    "substring_matches": substring_matches,
                    "all_substrings_match": all(substring_matches.values()),
                }
            )

    return cases


def evaluate_contract() -> dict[str, Any]:
    source = parse_summary_contract(_load_text(SUMMARY_TOOL))
    render_cases = evaluate_render_cases()
    consistency = {
        "source_complete": all(bool(value) for value in source.values()),
        "render_cases_match_expected": all(
            bool(item["all_substrings_match"]) for item in render_cases
        ),
    }
    consistency["all_checks_passed"] = all(bool(value) for value in consistency.values())
    return {
        "source": source,
        "render_cases": render_cases,
        "consistency": consistency,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="AKVC macOS validation-session summary contract checker"
    )
    parser.add_argument("--output")
    args = parser.parse_args(argv)

    payload = evaluate_contract()
    rendered = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    print(rendered)
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(rendered + "\n", encoding="utf-8")

    if not bool(payload["consistency"]["all_checks_passed"]):
        return 3
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
